version: '3'

tasks:
  default:
    cmds:
      - task --list

  run:
    desc: Runs the script with the provided name (clean, upgrade, install)
    cmds:
      - sh scripts/{{.CLI_ARGS}}.sh

  setup:
    desc: Setups the complete dev environment (installing dependencies, bootstrapping the database)
    cmds:
      - docker compose -f  backend/docker/docker-compose.dev.yml --env-file backend/app/.env.development -p sqliqour-dev up -d
      - sleep 5
      - cd backend/app && bun drizzle:migrate

  test-deployment:
    desc: Starts the production containers
    cmds:
      - docker compose -f deploy/docker-compose.prod.yml --env-file deploy/.env.production -p sqliqour-prod up -d --build

  stop:
    desc: Stops the dev environment
    cmds:
      - docker compose -f  backend/docker/docker-compose.dev.yml --env-file backend/app/.env.development -p sqliqour-dev down
      - docker compose -f  deploy/docker-compose.prod.yml --env-file deploy/.env.production -p sqliqour-prod down
