version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    networks:
      - sqliqour-network
    volumes:
      - database:/data/postgres

  sandbox-database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - ${SANDBOX_DATABASE_PORT}:${SANDBOX_DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${SANDBOX_DATABASE_ROOT_PASSWORD}
    networks:
      - sqliqour-network
    volumes:
      - sandbox-database:/var/lib/mysql:rw
    user: mysql

networks:
  sqliqour-network:
    driver: bridge

volumes:
  database:
    driver: local
  sandbox-database:
    driver: local
