version: '3'

services:
  database:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - database:/data/postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sandbox-database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - ${SANDBOX_DATABASE_PORT}:${SANDBOX_DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${SANDBOX_DATABASE_ROOT_PASSWORD}
    volumes:
      - sandbox-database:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  directus-cms:
    image: directus/directus:latest
    restart: unless-stopped
    volumes:
      - ./cms/uploads:/directus/uploads
      - ./cms/database:/directus/database
    ports:
      - 8055:8055
    environment:
      KEY: "sqliquor"
      SECRET: "sqliquor"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/database.sql"
      ADMIN_EMAIL: "admin@sql.de"
      ADMIN_PASSWORD: "admin"
      CORS_ENABLED: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  database:
  sandbox-database:
