/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 frontend/app/public/demolevel.glb
*/

import { useGLTF } from '@react-three/drei';

export function DemoLevel(props) {
  const { nodes, materials } = useGLTF('/demolevel.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Text.geometry}
        material={materials.Material}
        position={[7.734, 2.758, -16.637]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.884}
      />
      <mesh
        geometry={nodes.Inside_Wall_2.geometry}
        material={nodes.Inside_Wall_2.material}
        position={[-16.286, 1, -1.548]}
        scale={[1, 1, 0.25]}
      />
      <mesh
        geometry={nodes.Inside_Wall.geometry}
        material={nodes.Inside_Wall.material}
        position={[0, 3, -17]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.25, 3, 16.75]}
      />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 0.081, 0]} scale={17} />
      <mesh geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-3.297, 0, 2.56]} />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[-1.818, 4.041, 0.699]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-0.47, 4.041, 14.647]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-0.218, 1, 16.747]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.25, 1, 16.75]}
      />
      <group position={[-19.919, -0.212, 0.468]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-51.572, 0.035, -41.707]} rotation={[0, 1.571, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-72.543, 0.035, -40.099]} rotation={[0, 1.571, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-0.904, -0.212, -19.039]} rotation={[0, -1.571, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[71.547, 0.019, -19.106]} rotation={[0, -Math.PI / 2, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[35.181, 0.019, -41.508]} rotation={[0, 1.571, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-60.459, -0.212, 15.421]} rotation={[0, 1.571, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-41.015, -0.212, 60.437]} rotation={[-Math.PI, 0, -Math.PI]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[59.433, -0.009, 40.955]} rotation={[0, -1.571, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[44.582, -0.017, 0.396]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[1.002, -0.01, 43.774]} rotation={[0, -Math.PI / 2, 0]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-41.075, 0.025, -60.663]} rotation={[-Math.PI, 0, -Math.PI]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01002.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01002_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-18.239, 0.021, -77.411]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01002.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01002_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-39.861, 0.028, -105.052]} rotation={[-Math.PI, 0, -Math.PI]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_01002.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_01002_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-18.446, 0, -43.322]} scale={3.333}>
        <mesh geometry={nodes.Mesh_Props_Light_02001.geometry} material={materials['M_LowPolyMegapolis_MAIN.001']} />
        <mesh geometry={nodes.Mesh_Props_Light_02001_1.geometry} material={materials.M_LowPolyMegapolis_Light} />
      </group>
      <group position={[-54.4, 0, 13.362]} scale={3.333}>
        <mesh
          geometry={nodes.Mesh_Props_BusStation_01001.geometry}
          material={materials['M_LowPolyMegapolis_MAIN.001']}
        />
        <mesh geometry={nodes.Mesh_Props_BusStation_01001_1.geometry} material={materials.M_LowPolyMegapolis_Glass} />
      </group>
      <mesh
        geometry={nodes.Hydrant001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-46.284, 0.065, 13.799]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1547414354_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-48.344, 4.32, -43.459]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1556808355_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[45.263, 39.981, -50.931]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1677680378_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.906, 0.06, -48.826]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1677680378_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.906, 0.06, -72.14]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1771392385_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-42.016, 3.504, 66.523]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1771392385_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.811, 3.271, 66.793]}
        rotation={[2.887, -0.038, 0.146]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1773224386_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-42.134, 1.624, 69.005]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1773224386_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.374, 0.068, 67.865]}
        rotation={[-0.067, -0.033, 0.039]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1786510388_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[52.964, 30.119, -60.569]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1792082390_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[48.105, 29.989, -60.53]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={4.5}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1794149391_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[49.266, 29.5, -64.122]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={4.5}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1846084401_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[17.759, -0.046, -46.697]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1856749403_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[49.746, 0.388, 10.25]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1856749403_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[51.59, 0.388, 10.25]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1856749403_StaticMe002.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[53.434, 0.388, 10.25]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1856749403_StaticMe003.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[55.278, 0.388, 10.25]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1861349405_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[9.457, 0.413, -46.714]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1861349405_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[11.303, 0.413, -46.714]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1861349405_StaticMe002.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[13.149, 0.413, -46.714]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1919107416_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.915, 0.36, 66.731]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1919107416_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.915, 0.36, 68.993]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1919107416_StaticMe002.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.915, 0.36, 71.392]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1926835418_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[66.516, -0.033, -58.026]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1940333423_StaticMe.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-41.889, 3.582, 71.431]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034088B01_1940333423_StaticMe001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[-42.436, 3.72, 66.618]}
        rotation={[-0.109, 0, 0.292]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[11.557, -0.259, 123.421]}
        rotation={[0, 1.571, 0]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4002.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-3.441, -0.259, 10.94]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4003.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-63.433, -0.259, 70.935]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4004.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-123.438, -0.259, 10.947]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4005.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[56.564, -0.259, 70.927]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4006.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-48.464, -0.259, -116.565]}
        rotation={[0, 1.571, 0]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4007.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-123.444, -0.259, -49.046]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4008.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-3.452, -0.259, -49.06]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4011.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[56.558, -0.259, 10.924]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Sidewalk_Tile_4012.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[11.532, -0.259, -116.571]}
        rotation={[0, 1.571, 0]}
        scale={2.5}
      />
      <mesh
        geometry={nodes.Road001.geometry}
        material={materials['door.001']}
        position={[-14.285, -0.5, 0]}
        scale={200}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1903187735_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[78.519, 0, 4.665]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1903187735_StaticMe002.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-61.13, 0, -158.997]}
        rotation={[0, 1.571, 0]}
        scale={5.657}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1905741736_StaticMe002.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-55.379, 0, 66.881]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1905741736_StaticMe003.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-75.688, 0, -121.831]}
        scale={6.52}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1907992737_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-2.885, 0, 100.528]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1922145738_StaticMeshCo.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-75.926, 0, 3.369]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1924082739_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-5.536, 0, -141.631]}
        rotation={[0, -1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1928173741_StaticMeshCo.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-54.895, 0, 0.764]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1942056744_StaticMeshCo.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-121.164, 0, -21.199]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1945351745_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[25.47, 0, -57.57]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1954216747_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[57.495, 0, -86.917]}
        rotation={[0, 1.571, 0]}
        scale={5.845}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1957630748_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-0.663, 0, 59.713]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1959490749_StaticMeshCo.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-4.024, 0, -53.787]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1961109750_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[101.633, 0, 2.838]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_1961109750_StaticMe002.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[0.933, 0, -118.252]}
        scale={4.779}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_2008750751_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-89.096, 0, -54.752]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_2018005752_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-59.283, 0, 56.545]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_2022019753_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[53.896, 0, -56.3]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_2024286754_StaticMe001.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[56.64, 0, -1.309]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_2024286754_StaticMe002.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-1.038, 0, 81.479]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.StaticMeshActor_UAID_50EBF6776034C68A01_2029163755_StaticMeshCo.geometry}
        material={materials.M_LowPolyMegapolis_MAIN}
        position={[-60.072, 0, -60.492]}
        scale={3}
      />
      <mesh
        geometry={nodes.glas001.geometry}
        material={materials['Material.006']}
        position={[5.313, 2.148, -16.696]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={23.201}
      />
      <mesh
        geometry={nodes.lemon001.geometry}
        material={materials['Material.008']}
        position={[5.313, 2.148, -16.696]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={23.201}
      />
      <mesh
        geometry={nodes.straw001.geometry}
        material={materials['Material.002']}
        position={[5.313, 2.148, -16.696]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={23.201}
      />
      <mesh
        geometry={nodes.SK_Vehicles_Car_29001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-26.041, -0.24, -14.056]}
        rotation={[0, 1.571, 0]}
        scale={3.333}
        castShadow={true}
        receiveShadow={true}
      />
      <mesh
        geometry={nodes.SK_Vehicles_Car_01001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-48.395, -0.227, -33.988]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={3.333}
        castShadow={true}
        receiveShadow={true}
      />
      <mesh
        geometry={nodes.SK_Vehicles_Car_18001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.001']}
        position={[-33.8, 0, 36.427]}
        rotation={[0, -1.571, 0]}
        scale={2.5}
        castShadow={true}
        receiveShadow={true}
      />
      <mesh
        geometry={nodes.SK_Props_HousePart_05001.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[61.426, 29.483, 9.117]}
        scale={3.333}
      />
      <mesh
        geometry={nodes.SK_Props_HousePart_05002.geometry}
        material={materials['M_LowPolyMegapolis_MAIN.002']}
        position={[61.426, 29.483, 11.778]}
        scale={3.333}
      />
    </group>
  );
}

useGLTF.preload('/demolevel.glb');
