name: Backend Deployment

on:
  push:
    tags:
      - '*'
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  deploy-frontend:
    name: deploy backend docker image
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    environment: production
    env:
      NODE_ENV: production
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx for Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
